apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: frappe-mariadb
  namespace: default
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-root-password
    key: password
  image: mariadb:10.11
  storage:
    size: 2Gi
  replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-root-password
  namespace: default
type: Opaque
stringData:
  password: frappe
---
apiVersion: v1
kind: Secret
metadata:
  name: e2e-admin-password
  namespace: default
type: Opaque
stringData:
  password: admin
---
apiVersion: vyogo.tech/v1alpha1
kind: FrappeBench
metadata:
  name: e2e-test-bench
  namespace: default
spec:
  frappeVersion: "version-15"
  storageClassName: "standard" 
  imageConfig:
    repository: ghcr.io/rmallam/frappe_docker
    # Note: The e2e-test workflow will replace this with a local image if needed,
    # but for manual/kind testing we use the verified production-ready image.
    tag: sha-ae82c47
    pullPolicy: IfNotPresent
  apps:
    - name: erpnext
      source: image
  redisConfig:
    type: redis
  workerAutoscaling:
    short:
      enabled: false
      staticReplicas: 0
    long:
      enabled: false
      staticReplicas: 0
    default:
      enabled: false
      staticReplicas: 1
---
apiVersion: vyogo.tech/v1alpha1
kind: FrappeSite
metadata:
  name: e2e-test-site
  namespace: default
spec:
  benchRef:
    name: e2e-test-bench
  siteName: e2e.localhost
  adminPasswordSecretRef:
    name: e2e-admin-password
  dbConfig:
    provider: mariadb
  ingress:
    enabled: true
    # Note: 'domain' is a top-level field in spec, not under ingress.
    # It defaults to siteName if not specified.
